language: ruby
rvm:
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - 1.9.3
  - rbx-2
  - ruby-head
  - ree
script: bundle exec rspec
cache: bundler
branches:
  except:
    - master
branches:
  only:
    - v0.2
addons:
  code_climate:
    repo_token: eb44970f9efc497fb68c6ec1ce051dea530776b6a5bbe75e57734625f761ac86