language: ruby
rvm:
  - ruby-head
  - 1.9.3
script: bundle exec rspec
cache: bundler
branches:
  except:
    - master
branches:
  only:
    - v0.2
addons:
  code_climate:
    repo_token: eb44970f9efc497fb68c6ec1ce051dea530776b6a5bbe75e57734625f761ac86